openapi: 3.0.0
info:
  title: Portfolio API
  version: 1.0.0
  description: 게시글 관련 엔드포인트 문서
servers:
  - url: http://localhost:3000

paths:
  /api/v1/posts:
    get:
      summary: 게시글 목록 조회
      description: 등록된 게시글 리스트를 반환합니다. (페이지네이션 적용 가능)
      parameters:
        - name: page
          in: query
          required: false
          schema: {type: integer, default: 1}
          description: 페이지 번호
        - name: pageSize
          in: query
          required: false
          schema: {type: integer, default: 10}
          description: 한 페이지에 표시할 게시글 수
      responses:
        '200':
          description: 성공
          content:
            application/json:
              example:
                page: 1
                pageSize: 10
                total: 25
                items:
                  - post_id: 1
                    title: 첫 번째 게시물
                    author: user1
                    view_count: 15
                    status: public
                    create_at: 2025-11-02
        '500': {description: 서버 오류}

  /api/v1/posts/{id}:
    get:
      summary: 게시글 상세 조회
      description: 특정 게시글 및 댓글 목록을 조회합니다.
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: integer, example: 1}
          description: 게시글 ID
      responses:
        '200':
          description: 성공
          content:
            application/json:
              example:
                post_id: 1
                title: 게시글 제목
                content: 본문 내용입니다.
                author: user1
                status: public
                view_count: 15
                created_at: 2025-11-02
                comments:
                  - comment_id: 1
                    content: 댓글입니다.
                    author: user2
                    create_at: 2025-11-02
        '404': {description: 게시글 없음}
        '500': {description: 서버 오류}
    delete:
      summary: 게시글 삭제 (soft delete)
      description: deleted_at에 시간이 기록되어 목록에서 제외됩니다.
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: integer}
          description: 게시글 ID
      responses:
        '204': {description: 성공 (본문 없음)}
        '404': {description: 게시글 없음}
        '500': {description: 서버 오류}

  /api/v1/posts/{postId}/comments/{commentId}:
    delete:
      summary: 댓글 삭제 (soft delete)
      description: deleted_at에 시간이 기록되어 댓글 목록에서 제외됩니다.
      parameters: 
        - in: path
          name: postId
          required: true
          schema: { type: integer, example: 1 }
          description: 게시글 ID
        - in: path
          name: commentId
          required: true
          schema: { type: integer, example: 1 }
          description: 댓글 ID
      responses:
        '204': {description: 성공 (본문 없음)}
        '404': {description: 댓글 없음}
        '500': {description: 서버 오류}

  /api/v1/posts/{id}/status:
    patch:
      summary: 게시글 상태 변경
      description: public | private | deleted 로 상태를 변경합니다.
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: integer}
          description: 게시글 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [public, private, deleted]
          example:
            status: private
      responses:
        '200':
          description: 성공
          content:
            application/json:
              example:
                message: 상태가 변경되었습니다.
                status: private
        '400': {description: 잘못된 상태 값}
        '404': {description: 게시글 없음}
        '500': {description: 서버 오류}

  /api/v1/posts/{id}/view:
    post:
      summary: 조회수 증가
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: integer}
          description: 게시글 ID
      responses:
        '204': {description: 성공 (본문 없음)}
        '404': {description: 게시글 없음}

